### ISSUE TITLE
pkg-resources

### ISSUE THREAD

**Issue by lukkie001** [dyh/unbox_yolov5_deepsort_counting#2]
No matching distribution found for pkg-resources
why?

**Comment by dyh** [comment]
安装哪个软件包的错误？

**Comment by jiangyuanlin01** [comment]
i have the same problem

**Comment by jiangyuanlin01** [comment]
ModuleNotFoundError: No module named 'cv2'

**Comment by jiangyuanlin01** [comment]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/root/unbox_yolov5_deepsort_counting-main/venv/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
这是什么原因
